services:
  - type: web
    name: estres-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: SERVICE_ACCOUNT_JSON
        fromDatabase: true  # ← Mejor que poner el JSON largo aquí
      - key: FIREBASE_API_KEY
        fromDatabase: true  # Te lo pedirá en el panel Render
      - key: COOKIE_SECRET
        value: supersecreto12345
