services:
  - type: web
    name: estres-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: SERVICE_ACCOUNT_JSON
      - key: FIREBASE_API_KEY
      - key: COOKIE_SECRET
        value: supersecreto12345
